signup page styled as login page
CyberCellGu/CyberCell-New pull request #36
Opened 2023-10-11 08:01 UTC by insane-22

Fixes #33 
Video of trial:- 
[Screencast from 11-10-23 01:25:16 PM IST.webm](https://github.com/CyberCellGu/CyberCell/assets/116253210/17abcb89-79d7-4e12-a3ed-f2cad95d1f1e)
Register page didn't look good with too many fields hence I commented them,
Any suggestions are highly welcome

2023-10-11 14:34 UTC, MSami625 approved these changes

2023-10-11 14:38 UTC, MSami625 requested changes
Although  you have done nice work but i have one point , on the Sign Up page the sign up form is too long vertically and is going out out view which has to be scrolled down to see whole form. Make it responsive and do the final changes.

2023-10-11 17:18 UTC, insane-22 commented
Thank you @MSami625 for your valuable inputs, I have made certain changes and this is how it looks now:-
[Screencast from 11-10-23 10:46:26 PM IST.webm](https://github.com/CyberCellGu/CyberCell/assets/116253210/7c8bcabf-6cc2-486e-a002-86102b2d07a9)
If there are some other changes, do share, I would be more than happy to add them

2023-10-12 18:41 UTC, MSami625 approved these changes
ok looks good , we can make it more responsive for mobile view.

2023-10-12 18:41 UTC, merged